{
    "DWF": {
        "references": [
            "https://security.alpinelinux.org/vuln/CVE-2018-1000808",
            "https://access.redhat.com/security/cve/CVE-2018-1000808",
            "https://www.suse.com/security/cve/CVE-2018-1000808/"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "cve@mitre.org",
            "DATE_ASSIGNED": "2018-10-05T22:22:07.612676",
            "DATE_REQUESTED": "2018-09-20T17:05:57",
            "ID": "CVE-2018-1000808",
            "REQUESTER": "secure@veritas.com",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "n/a",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "n/a"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "n/a"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://github.com/pyca/pyopenssl/pull/723",
                    "refsource": "CONFIRM",
                    "url": "https://github.com/pyca/pyopenssl/pull/723"
                },
                {
                    "name": "RHSA-2019:0085",
                    "refsource": "REDHAT",
                    "url": "https://access.redhat.com/errata/RHSA-2019:0085"
                },
                {
                    "name": "USN-3813-1",
                    "refsource": "UBUNTU",
                    "url": "https://usn.ubuntu.com/3813-1/"
                },
                {
                    "name": "openSUSE-SU-2019:1104",
                    "refsource": "SUSE",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": [
                {
                    "children": [],
                    "cpe_match": [
                        {
                            "cpe23Uri": "cpe:2.3:a:pyopenssl_project:pyopenssl:*:*:*:*:*:*:*:*",
                            "cpe_name": [],
                            "versionEndExcluding": "17.5.0",
                            "vulnerable": true
                        }
                    ],
                    "operator": "OR"
                },
                {
                    "children": [],
                    "cpe_match": [
                        {
                            "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
                            "cpe_name": [],
                            "vulnerable": true
                        }
                    ],
                    "operator": "OR"
                },
                {
                    "children": [],
                    "cpe_match": [
                        {
                            "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
                            "cpe_name": [],
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*",
                            "cpe_name": [],
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
                            "cpe_name": [],
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:a:redhat:openstack:13:*:*:*:*:*:*:*",
                            "cpe_name": [],
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:a:redhat:gluster_storage:3.0:*:*:*:*:*:*:*",
                            "cpe_name": [],
                            "vulnerable": true
                        }
                    ],
                    "operator": "OR"
                }
            ]
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@mitre.org",
                "ID": "CVE-2018-1000808"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "en",
                                "value": "CWE-404"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/pyca/pyopenssl/pull/723",
                        "refsource": "CONFIRM",
                        "tags": [
                            "Patch",
                            "Third Party Advisory"
                        ],
                        "url": "https://github.com/pyca/pyopenssl/pull/723"
                    },
                    {
                        "name": "USN-3813-1",
                        "refsource": "UBUNTU",
                        "tags": [
                            "Third Party Advisory"
                        ],
                        "url": "https://usn.ubuntu.com/3813-1/"
                    },
                    {
                        "name": "RHSA-2019:0085",
                        "refsource": "REDHAT",
                        "tags": [
                            "Third Party Advisory"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:0085"
                    },
                    {
                        "name": "openSUSE-SU-2019:1104",
                        "refsource": "SUSE",
                        "tags": [],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
                    }
                ]
            }
        },
        "impact": {
            "baseMetricV2": {
                "acInsufInfo": false,
                "cvssV2": {
                    "accessComplexity": "MEDIUM",
                    "accessVector": "NETWORK",
                    "authentication": "NONE",
                    "availabilityImpact": "PARTIAL",
                    "baseScore": 4.3,
                    "confidentialityImpact": "NONE",
                    "integrityImpact": "NONE",
                    "vectorString": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
                    "version": "2.0"
                },
                "exploitabilityScore": 8.6,
                "impactScore": 2.9,
                "obtainAllPrivilege": false,
                "obtainOtherPrivilege": false,
                "obtainUserPrivilege": false,
                "severity": "MEDIUM",
                "userInteractionRequired": false
            },
            "baseMetricV3": {
                "cvssV3": {
                    "attackComplexity": "HIGH",
                    "attackVector": "NETWORK",
                    "availabilityImpact": "HIGH",
                    "baseScore": 5.9,
                    "baseSeverity": "MEDIUM",
                    "confidentialityImpact": "NONE",
                    "integrityImpact": "NONE",
                    "privilegesRequired": "NONE",
                    "scope": "UNCHANGED",
                    "userInteraction": "NONE",
                    "vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "version": "3.0"
                },
                "exploitabilityScore": 2.2,
                "impactScore": 3.6
            }
        },
        "lastModifiedDate": "2020-10-15T13:28Z",
        "publishedDate": "2018-10-08T15:29Z"
    }
}